language : node_js

node_js:
  - "9"

install: yarn

cache: yarn

git:
  depth: 1

script:
  - yarn start

branches:
  except:
    - master
    - /^test-.*$/

jobs:
  include:
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm run build
        - echo "NPM Building Finished."

      deploy:
        provider: npm
        email: "529360897@qq.com"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
        edge: true
