# https://travis-ci.org/jf3096/test-travis

# 使用 nodejs
language: node_js

# 版本为 8
node_js:
  - "9"

# 使用 yarn 而不是 npm (按照实际情况调整)
install: yarn
cache: yarn

git:
  depth: 1

script:
  - yarn start

branches:
  only:
    - gh-pages
    - /.*/
  except:
  #    - master
  - /^test-.*$/

jobs:
  include:
    - stage: deploy
      script:
        - if [[ $TRAVIS_COMMIT_MESSAGE == "release:"* ]]; then echo "开始执行部署 ..." ; npm run build ; echo "部署完成" ; fi ;
      deploy:
        provider: npm
        email: "529360897@qq.com"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
          condition: $TRAVIS_COMMIT_MESSAGE == "release:"*
        edge: true
