# https://travis-ci.org/jf3096/test-travis
language: node_js

node_js:
  - "9"

install: yarn
cache: yarn

git:
  depth: 1

script:
  - yarn start

branches:
  only:
    - gh-pages
    - /.*/
  except:
  #    - master
  - /^test-.*$/

jobs:
  include:
    - stage: deploy
      script:
        - npx npm-version-process
        - echo "开始执行部署 ..."
        - yarn run build
        - yarn publish
        - echo "部署完成"

      deploy:
        provider: npm
        email: "529360897@qq.com"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
        edge: true
